{
 "title": "Fix Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"fixdgnultrasonic\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dataOnline\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"1101\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> last()\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Lowest Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"fixdgnultrasonic\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dataOnline\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"1101\")\r\n  |> min()\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Temperature History",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"fixdgnultrasonic\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dataOnline\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"1101\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Offline Temperature History",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"fixdgnultrasonic\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r._measurement == \"dataOffline\")\r\n  |> filter(fn: (r) => \r\n    r._field == \"rtc\" or\r\n    r._field == \"temperature\" or\r\n    r._field == \"humidity\" or\r\n    r._field == \"distance\"\r\n  )\r\n  // 1) Pivot so we get columns: rtc, temperature, humidity, distance, etc.\r\n  |> pivot(\r\n    rowKey:[\"_time\"],\r\n    columnKey:[\"_field\"],\r\n    valueColumn:\"_value\"\r\n  )\r\n  // 2) Rename the original _time to something else\r\n  |> rename(columns: {_time: \"insertion_time\"})\r\n\r\n  // 3) Parse the \"rtc\" string into a Flux time\r\n  |> map(fn: (r) => ({\r\n    r with parsedTime: time(v: r.rtc)\r\n  }))\r\n\r\n  // 4) Rename parsedTime -> _time\r\n  |> rename(columns: {parsedTime: \"_time\"})\r\n\r\n  // 5) Shift _time by -7 hours (because the time got shifted again)\r\n  |> timeShift(duration: -7h, columns: [\"_time\"])\r\n\r\n  // 6) (Optional) drop the old rtc column if you dont need it\r\n  |> drop(columns: [\"rtc\"])\r\n  |> drop(columns: [\"insertion_time\"])\r\n  |> drop(columns: [\"_start\"])\r\n  |> drop(columns: [\"_stop\"])\r\n  |> drop(columns: [\"humidity\"])\r\n  |> drop(columns: [\"distance\"])\r\n\r\n  // Now you have:\r\n  //   insertion_time (original time),\r\n  //   _time (from your rtc field),\r\n  //   temperature, humidity, distance, etc."
    }
   ]
  },
  {
   "title": "Peak Temperatures",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"fixdgnultrasonic\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dataOnline\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"1101\")\r\n  |> max()\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"fixdgnultrasonic\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dataOnline\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"1101\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\r\n  |> last()\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Lowest Humidity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"fixdgnultrasonic\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dataOnline\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"1101\")\r\n  |> min()\r\n  |> yield(name: \"last\")\r\n  "
    }
   ]
  },
  {
   "title": "Humidity History",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"fixdgnultrasonic\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dataOnline\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"1101\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Offline Humidity History",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"fixdgnultrasonic\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r._measurement == \"dataOffline\")\r\n  |> filter(fn: (r) => \r\n    r._field == \"rtc\" or\r\n    r._field == \"temperature\" or\r\n    r._field == \"humidity\" or\r\n    r._field == \"distance\"\r\n  )\r\n  // 1) Pivot so we get columns: rtc, temperature, humidity, distance, etc.\r\n  |> pivot(\r\n    rowKey:[\"_time\"],\r\n    columnKey:[\"_field\"],\r\n    valueColumn:\"_value\"\r\n  )\r\n  // 2) Rename the original _time to something else\r\n  |> rename(columns: {_time: \"insertion_time\"})\r\n\r\n  // 3) Parse the \"rtc\" string into a Flux time\r\n  |> map(fn: (r) => ({\r\n    r with parsedTime: time(v: r.rtc)\r\n  }))\r\n\r\n  // 4) Rename parsedTime -> _time\r\n  |> rename(columns: {parsedTime: \"_time\"})\r\n\r\n  // 5) Shift _time by -7 hours (because the time got shifted again)\r\n  |> timeShift(duration: -7h, columns: [\"_time\"])\r\n\r\n  // 6) (Optional) drop the old rtc column if you dont need it\r\n  |> drop(columns: [\"rtc\"])\r\n  |> drop(columns: [\"insertion_time\"])\r\n  |> drop(columns: [\"_start\"])\r\n  |> drop(columns: [\"_stop\"])\r\n  |> drop(columns: [\"humidity\"])\r\n  |> drop(columns: [\"temperature\"])\r\n\r\n  // Now you have:\r\n  //   insertion_time (original time),\r\n  //   _time (from your rtc field),\r\n  //   temperature, humidity, distance, etc."
    }
   ]
  },
  {
   "title": "Peak Humidity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"fixdgnultrasonic\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dataOnline\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"1101\")\r\n  |> max()\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Distance",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "cm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"fixdgnultrasonic\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dataOnline\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"1101\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"distance\")\r\n  |> last()\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Lowest Distance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "cm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"fixdgnultrasonic\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dataOnline\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"distance\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"1101\")\r\n  |> min()\r\n  |> yield(name: \"last\")\r\n  "
    }
   ]
  },
  {
   "title": "Distance History",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "cm" } },
   "targets": [
    {
     "query": "from(bucket: \"fixdgnultrasonic\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dataOnline\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"1101\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"distance\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Offline Distance History",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "cm" } },
   "targets": [
    {
     "query": "from(bucket: \"fixdgnultrasonic\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r._measurement == \"dataOffline\")\r\n  |> filter(fn: (r) => \r\n    r._field == \"rtc\" or\r\n    r._field == \"temperature\" or\r\n    r._field == \"humidity\" or\r\n    r._field == \"distance\"\r\n  )\r\n  // 1) Pivot so we get columns: rtc, temperature, humidity, distance, etc.\r\n  |> pivot(\r\n    rowKey:[\"_time\"],\r\n    columnKey:[\"_field\"],\r\n    valueColumn:\"_value\"\r\n  )\r\n  // 2) Rename the original _time to something else\r\n  |> rename(columns: {_time: \"insertion_time\"})\r\n\r\n  // 3) Parse the \"rtc\" string into a Flux time\r\n  |> map(fn: (r) => ({\r\n    r with parsedTime: time(v: r.rtc)\r\n  }))\r\n\r\n  // 4) Rename parsedTime -> _time\r\n  |> rename(columns: {parsedTime: \"_time\"})\r\n\r\n  // 5) Shift _time by -7 hours (because the time got shifted again)\r\n  |> timeShift(duration: -7h, columns: [\"_time\"])\r\n\r\n  // 6) (Optional) drop the old rtc column if you dont need it\r\n  |> drop(columns: [\"rtc\"])\r\n  |> drop(columns: [\"insertion_time\"])\r\n  |> drop(columns: [\"_start\"])\r\n  |> drop(columns: [\"_stop\"])\r\n  |> drop(columns: [\"humidity\"])\r\n  |> drop(columns: [\"temperature\"])\r\n\r\n  // Now you have:\r\n  //   insertion_time (original time),\r\n  //   _time (from your rtc field),\r\n  //   temperature, humidity, distance, etc."
    }
   ]
  },
  {
   "title": "Peak Distance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "cm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"fixdgnultrasonic\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dataOnline\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"distance\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"1101\")\r\n  |> max()\r\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}